authn:
  oidc:
    clientId: "foo"
    clientSecret: "bar"
    wellKnown: ".well_known"
authz:
  opa:
    host: "opa"
    decision: httpapi/authz
debug: false

image:
  repository: ghcr.io/diamondjoseph/python-auth-example
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  type: ClusterIP

ingress:
  host: chart-example.local
