apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-auth-example
spec:
  rules:
    - host: {{ required "ingress.host" .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: python-auth-example
                port:
                  number: 80
  defaultBackend:
    service:
      name: python-auth-example
      port:
        number: 80
