apiVersion: v1
kind: Service
metadata:
  name: python-auth-example
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
      {{- if .Values.debug }}
    - port: 5678
      targetPort: debug
      name: debug
      {{- end }}
  selector:
    app: python-auth-example
