apiVersion: v1
kind: Service
metadata:
  name: python-auth-example
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: python-auth-example
